bookst/urls.py
from django.urls import path, include
from .views import new, create, detail, edit, update, delete


app_name = "bookst"

urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('<int:post_id>/', detail, name="detail"),
    path('edit/<int:post_id>/', edit, name="edit"),
    path('update/<int:post_id>/', update, name="update"),
    path('delete/<int:post_id>/', delete, name="delete"),
]


common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from bookst import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('bookst/', include('bookst.urls')),
    path('common/', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookst/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Post(models.Model):
    class Meta:
        ordering = ['-created_at']

    POST_TYPES = [
        (0, '기타'),
        (1, '소설'),
        (2, '시/에세이'),
        (3, '경제/경영'),
        (4, '자기계발')
    ]
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50,
                             verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    view_count = models.IntegerField(default=0,
                                     verbose_name="조회 수")

    _type = models.PositiveSmallIntegerField(choices=POST_TYPES,
                                             verbose_name="종류")
    image = models.ImageField(upload_to='bookst/image', default='bookst/default/기본이미지.jpg')

    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name="생성 시간")
    updated_at = models.DateTimeField(auto_now=True,
                                      verbose_name="수정 시간")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('bookst:detail', args=[self.pk])


common/models.py
from django.db import models

# Create your models here.

bookst/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    _type = forms.ChoiceField(widget=forms.RadioSelect,
                              label='종류',
                              choices=Post.POST_TYPES,
                              required=True
                              )
    class Meta:
        model = Post
        fields = ['title', '_type', 'content', 'image']
        labels = {
            'title': '제목',
            'content': '내용',
            'image': '이미지',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

bookst/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
import pdb


def main(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'bookst/main.html', context)


@login_required(login_url='common:login')
def new(request):
    form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'bookst/new.html', context)


@require_POST
def create(request):
    form = PostForm(request.POST, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
    # pdb.set_trace()
    # title = request.POST.get('title')
    # content = request.POST.get('content')
    # # Post(title=title, content=content).save()
    # Post.objects.create(title=title, content=content)
    return redirect(form.instance)


def detail(request, post_id):
    # post_id = request.GET.get('post_id')
    # post = Post.objects.get(pk=post_id)
    post = get_object_or_404(Post, pk=post_id)
    default_view_count = post.view_count
    post.view_count = default_view_count + 1
    post.save()
    context = {
        'post': post
    }
    return render(request, 'bookst/detail.html', context)


@login_required(login_url='common:login')
def edit(request, post_id):
    # post = Post.objects.get(pk=post_id)
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, "수정 권한이 없습니다.")
        return redirect('bookst:detail', post_id=post_id)
    context = {
        'post': post,
        'form': PostForm(instance=post)
    }
    return render(request, 'bookst/edit.html', context)



@require_POST
def update(request, post_id):
    # post = Post.objects.get(pk=post_id)
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
    return redirect(post)


@require_POST
def delete(request, post_id):
    # post = Post.objects.get(pk=post_id)
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('main')

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('main')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

bookst/templates/bookst/_form.html
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{{ btn_value }}" class="btn btn-outline-primary">

bookst/templates/bookst/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5 mb-3 d-flex flex-column align-items-center">
    <h1 class="fw-bold mb-5">Book Stargram</h1>
    <div class="card mb-3 ps-5 pe-5" style="max-width: 50rem;">
      {% if post.image %}
         <img src="{{ post.image.url }}" class="card-img-top" alt="...">
      {% endif %}
      <div class="card-body">
        <h3 class="card-title">{{ post.title }}</h3>
        <p class="card-text">{{ post.content }}</p>
        <div class="d-flex justify-content-between align-items-center">
            {% if request.user == post.author %}
            <div class="btn-group">
               <a href="{% url 'bookst:edit' post.pk %}" type="button" class="btn btn-sm btn-outline-info">Edit</a>
               <a href="#" type="button" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</a>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">삭제 확인</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    정말로 삭제하시겠습니까?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <form action="{% url 'bookst:delete' post.pk %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="삭제하기" class="btn btn-outline-secondary">
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- end Modal -->
            {% else %}
            <div class="btn-group">
               <button type="button" class="btn btn-sm btn-outline-secondary" disabled>Edit</button>
               <button type="button" class="btn btn-sm btn-outline-secondary" disabled>Delete</button>
            </div>
            {% endif %}

            <div class="d-flex flex-column">
              <small class="text-muted">{{ post.created_at }}</small>
              <small class="text-muted">글쓴이: {{ post.author }}</small>
              <small class="text-muted">조회 수: {{ post.view_count }}</small>
            </div>
        </div>


      </div>
    </div>
</div>
{% endblock %}

bookst/templates/bookst/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="mt-5">
        Edit Post
    </h1>
    <form action="{% url 'bookst:update' post.pk %}" method="POST" enctype="multipart/form-data">
        {% include 'bookst/_form.html' with form=form btn_value='글 수정' %}
    </form>
</div>
{% endblock %}

bookst/templates/bookst/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'CSS/main.css' %}">
  <section class="bg_img py-5 text-center">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-bolder">Book Stargram</h1>
        <br>
        <p class="lead text-muted">Remember And Recommend <br> What You've Read</p>
        <br>
        <p>
          <a href="{% url 'bookst:new' %}" class="btn btn-dark bg-gradient my-2 p-3 rounded-pill">책 자랑하기</a>
        </p>
      </div>
    </div>
  </section>
  <div class="album py-2">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for post in posts %}
        <div class="col">
          <div class="card shadow-sm">
            {% if post.image %}
<!--            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>-->
            <img src="{{ post.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
              <h4 class="card-text mb-3">{{ post.title }}</h4>
              <p class="card-text mb-3">{{ post.content }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{{ post.get_absolute_url }}" type="button" class="btn btn-sm btn-outline-success rounded-pill me-2">View</a>
                  {% if request.user == post.author %}
                  <a href="{% url 'bookst:edit' post.pk %}" type="button" class="btn btn-sm btn-outline-info rounded-pill">Edit</a>
                  {% else %}
                  <a href="#" type="button" class="btn btn-sm btn-outline-secondary rounded-pill" data-bs-toggle="modal" data-bs-target="#exampleModal">Edit</a>
                  {% endif %}
                </div>
                <div class="d-flex flex-column">
                  <small class="text-muted">{{ post.created_at }}</small>
                  <small class="text-muted">글쓴이: {{ post.author }}</small>
                  <small class="text-muted">조회 수: {{ post.view_count }}</small>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">본인 확인</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        본인이 아니면 수정할 수 없습니다.
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- end Modal -->
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

bookst/templates/bookst/new.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1 class="mt-5">
        New Post
    </h1>
    <form action="{% url 'bookst:create' %}" method="POST" enctype="multipart/form-data">
        {% include 'bookst/_form.html' with form=form btn_value="글 작성" %}
<!--        <div class="form-group">-->
<!--            <label>글 제목</label>-->
<!--            <input type="text" class="form-control" name="title">-->
<!--        </div>-->
<!--        <div class="form-group">-->
<!--            <label>글 내용</label>-->
<!--            <textarea class="form-control" name="content"></textarea>-->
<!--        </div>-->

<!--        ---------------나중에 수정할 모양 ----------------------->
<!--        이 사이트 이용해서 수정하기 -->
<!--        https://codepen.io/MR_RooT/pen/RwPErrB-->
<!--          <img src="..." class="card-img-top" alt="...">-->
<!--          <div class="card-body">-->
<!--            <h5 class="card-title">Card title</h5>-->
<!--            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>-->
<!--            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>-->
<!--          </div>-->

    </form>
</div>
{% endblock %}

templates/base.html

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Album example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">

<!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


  </head>
  <body>

<header>
  <div class="collapse bg-dark bg-gradient" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">What is this Site?</h4>

          <p class="text-muted">You can upload what you've read before and show others. </br>
            You should remember what you've read and recommend your favorite books.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Status</h4>
          <ul class="list-unstyled">
            {% if user.is_authenticated %}
            <li class="text-white fw-bold">{{ user.username }}</li>
            <a href="{% url 'common:logout' %}" class="text-white text-decoration-none">(로그아웃)</a>
            {% else %}
            <li><a href="{% url 'common:login' %}" class="text-white">로그인</a></li>
            {% endif %}
<!--            <li><a href="#" class="text-white">Like on Facebook</a></li>-->
<!--            <li><a href="#" class="text-white">Email me</a></li>-->
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark bg-gradient shadow-sm">
    <div class="container">
      <a href="{% url 'main' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Book stargram</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
    {% block content %}
    {% endblock %}
</main>

<footer class="text-muted py-5">
<!--  <div class="container">-->
<!--    <p class="float-end mb-1">-->
<!--      <a href="#">Back to top</a>-->
<!--    </p>-->
<!--    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>-->
<!--    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p>-->
<!--  </div>-->
</footer>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


  </body>
</html>

templates/common/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Signin Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">



    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'CSS/sign_in.css' %}">
  </head>
  <body class="text-center">

<main class="form-signin">
  <form method="POST" class="post-form" action="{% url 'common:login' %}">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <span style="color: #0984e3">
      <a href="{% url 'main' %}"><i class="fas fa-book fa-3x mb-3"></i></a>
    </span>
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
    <label for="username" class="visually-hidden">사용자이름</label>
    <input type="text" name="username" id="username" class="form-control mb-3" placeholder="Username" required autofocus
    value="{{ form.username.value|default_if_none:'' }}">
    <label for="password" class="visually-hidden">비밀번호</label>
    <input type="password" name="password" id="password" class="form-control" placeholder="Password" required
    value="{{ form.password.value|default_if_none:'' }}">
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary mb-3" type="submit">로그인</button>
    <a href="{% url 'common:signup' %}" class="w-100 btn btn-lg btn-primary">회원가입</a>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
  </form>
</main>


<script
    src="https://kit.fontawesome.com/6478f529f2.js"
    crossorigin="anonymous"></script>
  </body>
</html>

templates/common/signup.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Signin Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">



    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'CSS/sign_in.css' %}">

  </head>
  <body class="text-center">

<main class="form-signin">
  <form method="POST" class="post-form">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <span style="color:#0984e3">
      <a href="{% url 'main' %}"><i class="fas fa-book fa-3x mb-3"></i></a>
    </span>
    <h1 class="h3 mb-5 fw-normal">Please Sign Up</h1>

    <div class="form-group mb-3">
        <label for="username" class="visually-hidden">사용자이름</label>
        <input type="text" name="username" id="username" class="form-control" placeholder="Username" required autofocus
        value="{{ form.username.value|default_if_none:'' }}">
    </div>

    <div class="form-group">
        <label for="password1" class="visually-hidden">비밀번호</label>
        <input type="password" name="password1" id="password1" class="form-control" placeholder="Password" required
        value="{{ form.password1.value|default_if_none:'' }}">
    </div>

    <div class="form-group">
        <label for="password2" class="visually-hidden">비밀번호</label>
        <input type="password" name="password2" id="password2" class="form-control" placeholder="Password" required
        value="{{ form.password2.value|default_if_none:'' }}">
    </div>

    <div class="form-group mb-3">
        <label for="email" class="visually-hidden">비밀번호</label>
        <input type="text" name="email" id="email" class="form-control" placeholder="email" required
        value="{{ form.email.value|default_if_none:'' }}">
    </div>

<!--    <div class="checkbox mb-3">-->
<!--      <label>-->
<!--        <input type="checkbox" value="remember-me"> Remember me-->
<!--      </label>-->
<!--    </div>-->
    <button type="submit" class="w-100 btn btn-lg btn-primary mb-3">회원가입</button>
    <a href="{% url 'common:login' %}" class="w-100 btn btn-lg btn-primary">로그인하러 가기</a>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
  </form>
</main>


<script
    src="https://kit.fontawesome.com/6478f529f2.js"
    crossorigin="anonymous"></script>
  </body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}